-- Oracle Spatial: Typ SDO_GEOMETRY - cwiczenia

-- Zad 1.A
CREATE TABLE FIGURY(
    ID NUMBER(1) PRIMARY KEY,
    KSZTALT MDSYS.SDO_GEOMETRY
);

-- Zad 1.B

-- Circle
INSERT INTO FIGURY VALUES(1,
   SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,4),
    SDO_ORDINATE_ARRAY(5,3, 7,5, 5,7)
  )
);

-- Square
INSERT INTO FIGURY VALUES(2,
   SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(1,1, 5,5)
  )
);

-- Compound Line String
INSERT INTO FIGURY VALUES(3,
   SDO_GEOMETRY(
    2002,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,4,3, 1,2,1, 3,2,1, 5,2,2),
    SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)
  )
);

-- Zad 1.C
INSERT INTO FIGURY VALUES(4,
   SDO_GEOMETRY(
    2002,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,4,3, 1,2,1, 2,2,1, 3,2,2),
    SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)
  )
);

-- Zad 1.D
SELECT ID, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01) FROM FIGURY;

-- Zad 1.E
DELETE FROM FIGURY WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01) != 'TRUE';

-- Zad 1.F
COMMIT;
