-- Oracle Spatial: Standard SQL/MM - cwiczenia

-- Zad 1.C
CREATE TABLE  MYST_MAJOR_CITIES(
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

-- Zad 1.D
INSERT INTO MYST_MAJOR_CITIES
    SELECT C.FIPS_CNTRY, C.CITY_NAME, TREAT(ST_POINT.FROM_SDO_GEOM(C.GEOM) AS ST_POINT) STGEOM FROM MAJOR_CITIES C;

-- Zad 2.A
INSERT INTO MYST_MAJOR_CITIES VALUES(
    'PL', 'Szczyrk', ST_POINT(19.036107, 49.718655, 8307)
);

-- Zad 3.A
CREATE TABLE MYST_COUNTRY_BOUNDARIES(
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR(40),
    STGEOM ST_MULTIPOLYGON
);

-- Zad 3.B
INSERT INTO MYST_COUNTRY_BOUNDARIES
    SELECT C.FIPS_CNTRY, C.CNTRY_NAME, ST_Multipolygon(C.GEOM) STGEOM FROM COUNTRY_BOUNDARIES C;

-- Zad 3.C
SELECT C.STGEOM.ST_GeometryType() TYP_OBIEKTU, count(*) ILE FROM MYST_COUNTRY_BOUNDARIES C GROUP BY C.STGEOM.ST_GeometryType();

-- Zad 3.D
SELECT C.STGEOM.ST_ISSIMPLE() FROM MYST_COUNTRY_BOUNDARIES C;

-- Zad 4.A
SELECT CN.CNTRY_NAME CNTRY_NAME, SUM(CN.STGEOM.ST_CONTAINS(CI.STGEOM)) COUNT FROM MYST_COUNTRY_BOUNDARIES CN, MYST_MAJOR_CITIES CI GROUP BY CN.CNTRY_NAME;

-- Zad 4.B
select A.CNTRY_NAME A_NAME, B.CNTRY_NAME B_NAME
from MYST_COUNTRY_BOUNDARIES A,
 MYST_COUNTRY_BOUNDARIES B
where A.STGEOM.ST_TOUCHES(B.STGEOM) = 1
and B.CNTRY_NAME = 'Czech Republic'; 

-- Zad 4.C
select distinct B.CNTRY_NAME, R.name
from MYST_COUNTRY_BOUNDARIES B, RIVERS R
where B.CNTRY_NAME = 'Czech Republic'
and ST_LINESTRING(R.GEOM).ST_INTERSECTS(B.STGEOM) = 1;

-- Zad 4.D
select TREAT(A.STGEOM.ST_UNION(B.STGEOM) as ST_POLYGON).ST_AREA() POWIERZCHNIA
from MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = 'Czech Republic'
and B.CNTRY_NAME = 'Slovakia';

-- Zad 4.E
select B.STGEOM OBIEKT, B.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)).ST_GEOMETRYTYPE() WEGRY_BEZ
from MYST_COUNTRY_BOUNDARIES B, WATER_BODIES W
where B.CNTRY_NAME = 'Hungary'
and W.name = 'Balaton';

-- Zad 5.A
select B.CNTRY_NAME POLSKA, count(*) ILE
from MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
where SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM,
 'distance=100 unit=km') = 'TRUE'
and B.CNTRY_NAME = 'Poland'
group by B.CNTRY_NAME;

-- Zad 5.B
insert into USER_SDO_GEOM_METADATA
 select 'MYST_MAJOR_CITIES', 'STGEOM',
 T.DIMINFO, T.SRID
 from ALL_SDO_GEOM_METADATA T
 where T.TABLE_NAME = 'MAJOR_CITIES';

-- Zad 5.C
create index MYST_MAJOR_CITIES_IDX on
 MYST_MAJOR_CITIES(STGEOM)
indextype IS MDSYS.SPATIAL_INDEX;

-- Zad 5.D
select B.CNTRY_NAME POLSKA, count(*) ILE
from MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
where SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM,
 'distance=100 unit=km') = 'TRUE'
and B.CNTRY_NAME = 'Poland'
group by B.CNTRY_NAME;

