-- Oracle Spatial: Uklady LRS - cwiczenia

-- Zad 1.A
create table A6_LRS(GEOM MDSYS.SDO_GEOMETRY);

-- Zad 1.B
select SR.ID,
 SDO_GEOM.SDO_LENGTH(SR.GEOM, 1, 'unit=km') DISTANCE,
 ST_LINESTRING(SR.GEOM) .ST_NUMPOINTS() ST_NUMPOINTS
from STREETS_AND_RAILROADS SR, MAJOR_CITIES C
where SDO_RELATE(SR.GEOM,
 SDO_GEOM.SDO_BUFFER(C.GEOM, 10, 1, 'unit=km'),
'MASK=ANYINTERACT') = 'TRUE'
and C.CITY_NAME = 'Koszalin';

insert into A6_LRS
 select SDO_LRS.CONVERT_TO_LRS_GEOM(SR.GEOM, 0, 276.681)
 from STREETS_AND_RAILROADS SR
 where SR.ID = 56;
 
-- Zad 1.C
SELECT 
    SDO_GEOM.SDO_LENGTH(A.GEOM, 1, 'unit=km') DISTANCE,
    ST_LINESTRING(A.GEOM).ST_NUMPOINTS() ST_NUMPOINTS
FROM 
    A6_LRS A;

-- Zad 1.D
UPDATE A6_LRS SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0,  276.681);

-- Zad 1.E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS','GEOM',
MDSYS.SDO_DIM_ARRAY(
 MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
 MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
 MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
 8307);
 
-- Zad 1.F
CREATE INDEX A6_LRS_idx ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
 
-- Zad 2.A
select SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500 FROM A6_LRS;

-- Zad 2.B
select SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT FROM A6_LRS;

-- Zad 2.C
select SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 from A6_LRS;

-- Zad 2.D
select SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPED from A6_LRS;

-- Zad 2.E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A.GEOM, SDO_LRS.PROJECT_PT(A.GEOM, C.GEOM)) WJAZD_NA_A6 
FROM A6_LRS A, MAJOR_CITIES C 
WHERE C.CITY_NAME = 'Slupsk';

-- Zad 2.F
select SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50,
 'unit=m arc_tolerance=1'), 1, 'unit=km') KOSZT
from A6_LRS A6, USER_SDO_GEOM_METADATA M
where M.TABLE_NAME = 'A6_LRS' and M.COLUMN_NAME = 'GEOM';


